#!/usr/bin/env bash
set -euo pipefail

docker run --rm \
  --add-host=host.docker.internal:host-gateway \
  -e DB_URL \
  -e DB_USERNAME \
  -e DB_PASSWORD \
  -e APP_TEMP_DIR \
  -v /saas/test-java:/workspace \
  -w /workspace \
  maven:3.9.9-eclipse-temurin-21 \
  mvn "$@"
